import { ArrowLeft, ArrowRight, Check, Mail } from "lucide-react";
import { Link, useRoute } from "wouter";
import { Navbar } from "@/components/sections/Navbar";
import { Footer } from "./Home";
import estrategiaImage from "@assets/generated_images/jcc-service-strategy-finance.jpg";
import costosImage from "@assets/generated_images/jcc-service-operational-costs.jpg";
import proyectosImage from "@assets/generated_images/jcc-service-projects-commercial.jpg";
import rentabilidadImage from "@assets/generated_images/jcc-service-sustainable-profitability.jpg";
import sapImage from "@assets/generated_images/jcc-sap-pmo.jpg";
import automatizacionImage from "@assets/generated_images/jcc-automatizacion.jpg";
import mapeoImage from "@assets/generated_images/jcc-mapeo-procesos.jpg";
import rpaImage from "@assets/generated_images/jcc-rpa.jpg";
import predictiveImage from "@assets/generated_images/jcc-modelos-predictivos.jpg";
import visionImage from "@assets/generated_images/jcc-computer-vision.jpg";
import architectureImage from "@assets/generated_images/jcc-arquitectura-datos.jpg";
import engineeringImage from "@assets/generated_images/jcc-data-engineering.jpg";
import powerBiImage from "@assets/generated_images/jcc-power-bi.jpg";
import excelImage from "@assets/generated_images/jcc-excel-modelamiento.jpg";
import projectImage from "@assets/generated_images/jcc-project-primavera.jpg";
import cloudImage from "@assets/generated_images/jcc-cloud-gobernanza.jpg";

const details: Record<string, { eyebrow: string; title: string; intro: string; body: string; image: string; points: string[]; next?: string }> = {
  "estrategia-finanzas": { eyebrow: "Servicios / 01", title: "Estrategia y finanzas corporativas", intro: "Alineamos la estrategia financiera con las decisiones que realmente mueven la operación minera.", body: "Construimos una lectura ejecutiva que conecta objetivos, capital de trabajo, CAPEX, caja y decisiones de inversión. El resultado es una agenda financiera con responsables, métricas y ritmo de gestión.", image: estrategiaImage, points: ["Planeamiento estratégico y Balanced Scorecard", "Control financiero, Working Capital y flujos de caja", "Modelos de valorización, M&A y decisiones de inversión", "Contabilidad de costos por departamentos y productos"], next: "excelencia-costos" },
  "excelencia-costos": { eyebrow: "Servicios / 02", title: "Excelencia operacional y costos", intro: "Cada desviación debe tener un driver, un responsable y una acción.", body: "Pasamos de una lectura contable tardía a un sistema de control que explica las brechas en volumen, precio, rendimiento, consumo e imputación. Así su equipo puede corregir, controlar, renegociar o actualizar el forecast.", image: costosImage, points: ["Gestión de costos y presupuestos Budget & Forecast", "Presupuesto Base Cero y control de desviaciones", "KPIs operativos y análisis de causas raíz", "Trazabilidad por mina, zona, labor, proceso y contrato"], next: "proyectos-comercial" },
  "proyectos-comercial": { eyebrow: "Servicios / 03", title: "Proyectos y gestión comercial", intro: "El capital compite: priorizamos proyectos por valor, riesgo y caja.", body: "Evaluamos expansiones, nuevos proyectos y decisiones comerciales con una lógica integrada. No miramos toneladas aisladas: conectamos calidad, términos, penalidades, logística, NSR, EBITDA y flujo de caja.", image: proyectosImage, points: ["Evaluación de proyectos y construcción del caso base", "Riesgo, VAN, TIR, WACC, Payback y sensibilidades", "Valorización de concentrados y maximización de NSR", "Compra de mineral y modelos económicos de acopio"], next: "rentabilidad" },
  "rentabilidad": { eyebrow: "Servicios / 04", title: "Rentabilidad que se sostiene", intro: "La consultoría termina cuando las capacidades quedan instaladas en su equipo.", body: "Diseñamos modelos de gestión que se incorporan a la rutina diaria, con transferencia de conocimiento, acompañamiento a usuarios clave y medición de beneficios capturados.", image: rentabilidadImage, points: ["Modelos de gestión adaptados al negocio", "Transferencia de conocimiento al equipo interno", "Gobernanza, responsables y seguimiento de acciones", "Medición de impacto y mejora continua"], next: "servicios" },
  "sap-pmo": { eyebrow: "Tecnología / SAP PMO", title: "Un ERP que entiende la realidad de su mina.", intro: "Somos el puente entre la operación minera y la tecnología.", body: "Actuamos como coordinadores del proyecto del lado de la mina, asegurando que SAP responda al proceso real antes de configurar. Acompañamos la estandarización, el modelo de costos y la adopción por parte de usuarios clave.", image: sapImage, points: ["Procesos end-to-end mina–planta–finanzas", "Modelo de costos y control CAPEX/OPEX", "Coordinación de proyecto y usuarios clave", "Gestión del cambio y adopción"], next: "automatizacion" },
  "automatizacion": { eyebrow: "Tecnología / FP&A", title: "Menos Excel manual. Más tiempo para decidir.", intro: "Llevamos la planificación financiera al siguiente nivel.", body: "Implementamos soluciones de FP&A automatizado, dashboards ejecutivos y Business Intelligence para acelerar el cierre y darle a la gerencia una lectura de KPIs en tiempo real.", image: automatizacionImage, points: ["FP&A automatizado y rolling forecast", "Dashboards ejecutivos con KPIs en tiempo real", "Conciliaciones, cargas y cierres automatizados", "Alianza tecnológica con Partner 247"], next: "mapeo-procesos" },
  "mapeo-procesos": { eyebrow: "Transformación digital / 01", title: "Mapeo de procesos: entender antes de automatizar.", intro: "Del proceso actual al modelo operativo que se puede mejorar.", body: "Levantamos y documentamos procesos BPMN de costos, valorizaciones y suministros. Identificamos cuellos de botella, roles, decisiones y fuentes antes de tocar cualquier sistema.", image: mapeoImage, points: ["Mapeo BPMN de procesos críticos", "Roles, decisiones y responsables", "Línea base y puntos de control", "Hoja de ruta priorizada"], next: "rpa" },
  "rpa": { eyebrow: "Transformación digital / 02", title: "Automatización robótica para quitar trabajo repetitivo.", intro: "La automatización libera tiempo para el análisis y la decisión.", body: "Diseñamos bots para conciliaciones, cargas, cierres y generación de reportes. Cada automatización se construye alrededor de un proceso trazable y medible.", image: rpaImage, points: ["RPA para conciliaciones y cargas", "Reducción del trabajo manual en Excel", "Reportes y cierres con menos errores", "Control de excepciones y auditoría"], next: "modelos-predictivos" },
  "modelos-predictivos": { eyebrow: "Transformación digital / 03", title: "Modelos predictivos para anticipar el futuro.", intro: "No solo reportar el pasado: anticipar fallas, costos y escenarios.", body: "Aplicamos Machine Learning y modelos supervisados o no supervisados para anticipar fallas de maquinaria, anomalías y variables operativas complejas.", image: predictiveImage, points: ["Forecast y sensibilidades operativas", "Detección de anomalías", "Predicción de fallas críticas", "Modelos explicables para la decisión"], next: "computer-vision" },
  "computer-vision": { eyebrow: "Transformación digital / 04", title: "Deep Learning y Computer Vision.", intro: "Convertimos imágenes y video en señales operativas.", body: "Implementamos redes neuronales profundas para procesamiento en tiempo real, control automatizado de leyes minerales y detección de anomalías industriales.", image: visionImage, points: ["Procesamiento de video e imágenes", "Control automatizado de leyes minerales", "Detección temprana de anomalías", "Integración con alertas y responsables"], next: "arquitectura-datos" },
  "arquitectura-datos": { eyebrow: "Transformación digital / 05", title: "Arquitectura de datos: SQL y Big Data.", intro: "Cada dato debe vivir en la arquitectura que le corresponde.", body: "Conectamos ERP, sistemas de mina, planeamiento, laboratorio, campo, archivos y sensores. SQL Server sostiene el núcleo transaccional; Data Lakes absorben el volumen masivo.", image: architectureImage, points: ["SQL Server y núcleo transaccional", "Data Lakes para sensores y campo", "Gobernanza y disponibilidad", "Fuentes conectadas con trazabilidad"], next: "data-engineering" },
  "data-engineering": { eyebrow: "Transformación digital / 06", title: "Python Pipelines y Data Engineering.", intro: "De múltiples fuentes a datos confiables para decidir.", body: "Construimos tuberías ETL automatizadas para limpiar, transformar y procesar datos provenientes de operaciones, finanzas, campo y sistemas corporativos.", image: engineeringImage, points: ["Pipelines ETL automatizados", "Limpieza y transformación masiva", "Integración de múltiples fuentes", "Datos listos para dashboards y modelos"], next: "estrategia-finanzas" },
  "power-bi": { eyebrow: "Tecnología / Business Intelligence", title: "Power BI para ver el negocio a tiempo.", intro: "Indicadores D+1 para actuar antes de que la brecha crezca.", body: "Diseñamos dashboards ejecutivos con una lectura Real vs Plan vs Budget vs Forecast, conectando los drivers operativos con EBITDA y caja.", image: powerBiImage, points: ["Dashboards ejecutivos", "KPIs operativos y financieros", "Alertas y seguimiento de acciones", "Lectura de brechas en tiempo real"], next: "excel-modelamiento" },
  "excel-modelamiento": { eyebrow: "Tecnología / Modelamiento", title: "Excel avanzado para decisiones complejas.", intro: "Cuando Excel es necesario, debe ser trazable, sólido y gobernado.", body: "Construimos modelos financieros y operativos para presupuestos, escenarios, CAPEX, forecast y business cases, reduciendo errores y trabajo repetitivo.", image: excelImage, points: ["Budget & Forecast", "Modelos financieros complejos", "Sensibilidades y escenarios", "Control presupuestario"], next: "power-bi" },
  "project-primavera": { eyebrow: "Tecnología / Proyectos", title: "MS Project y Primavera P6.", intro: "El cronograma como sistema de control, no como documento estático.", body: "Ordenamos cronogramas maestros, ruta crítica, hitos y dependencias para que la dirección entienda cómo el tiempo cambia el capital y la caja.", image: projectImage, points: ["Cronogramas maestros", "Ruta crítica y dependencias", "Control de avances", "Impacto en CAPEX y caja"], next: "cloud-gobernanza" },
  "cloud-gobernanza": { eyebrow: "Tecnología / Gobernanza", title: "Integración Cloud y gobernanza.", intro: "Datos disponibles, seguros y con responsables claros.", body: "Sincronizamos datos entre campo y oficina central, creando reglas de acceso, calidad, disponibilidad y cumplimiento para sostener la operación.", image: cloudImage, points: ["Integración segura entre fuentes", "Gobernanza y calidad de datos", "Disponibilidad para equipos ejecutivos", "Cumplimiento y control de acceso"], next: "sap-pmo" },
};

export default function DetailPage() {
  const [, params] = useRoute("/detalle/:slug");
  const detail = details[params?.slug ?? ""] ?? details["estrategia-finanzas"];
  const isServiceDetail = detail.eyebrow.startsWith("Servicios");
  const isLastService = detail.next === "servicios";
  return <div className="site-page"><Navbar /><main className="detail-page"><div className="detail-breadcrumb"><Link href="/servicios"><ArrowLeft size={15} /> Volver a la vista general</Link></div><section className="detail-hero"><div><p className="eyebrow">{detail.eyebrow}</p><h1>{detail.title}</h1><p className="detail-intro">{detail.intro}</p></div><img src={detail.image} alt={`JCC Consulting: ${detail.title}`} /></section><section className="detail-body"><div><p className="eyebrow">Cómo ayudamos</p><p className="detail-copy">{detail.body}</p><Link href="/contacto" className="button button-dark"><Mail size={16} /> Conversar con un especialista</Link></div><div className="detail-points"><p className="eyebrow">Alcance</p>{detail.points.map(point => <div key={point}><Check size={17} /> <span>{point}</span></div>)}</div></section>{isServiceDetail && <section className="detail-next"><div><p className="eyebrow">{isLastService ? "Vista general" : "Siguiente servicio"}</p><h2>{isLastService ? "Vuelva a revisar los cuatro servicios de JCC Consulting." : "Explore el siguiente servicio y conecte cada decisión con el resto del negocio."}</h2></div><Link href={isLastService ? "/servicios" : `/detalle/${detail.next}`} className="detail-next-link">{isLastService ? "Ver los 4 servicios" : "Continuar explorando"} <ArrowRight size={16} /></Link></section>}</main><Footer /></div>;
}