import { ArrowRight, BriefcaseBusiness, Calculator, Crosshair, TrendingUp } from "lucide-react";
import { Link } from "wouter";
import { Navbar } from "@/components/sections/Navbar";
import { Footer } from "./Home";
import mineralImage from "@assets/generated_images/jcc-mineral-detail.jpg";
import strategyImage from "@assets/generated_images/jcc-service-strategy-finance.jpg";
import costsImage from "@assets/generated_images/jcc-service-operational-costs.jpg";
import projectsImage from "@assets/generated_images/jcc-service-projects-commercial.jpg";
import profitabilityImage from "@assets/generated_images/jcc-service-sustainable-profitability.jpg";

const groups = [
  { id: "estrategia", detailSlug: "estrategia-finanzas", icon: Crosshair, number: "01", title: "Estrategia y finanzas corporativas", intro: "Alineamos las decisiones financieras con lo que realmente ocurre en la operación.", image: strategyImage, items: ["Planeamiento estratégico y Balanced Scorecard", "Planeamiento y control financiero", "Gestión de Working Capital, CAPEX y flujos de caja", "Valorización de empresas y M&A"] },
  { id: "costos", detailSlug: "excelencia-costos", icon: Calculator, number: "02", title: "Excelencia operacional y costos", intro: "Convertimos el control de costos en una herramienta para crecer, no solo para reportar.", image: costsImage, items: ["Gestión de costos y presupuestos (Budget & Forecast)", "Presupuesto Base Cero", "Productividad y control de gestión", "KPIs operativos y análisis de causas raíz"] },
  { id: "proyectos", detailSlug: "proyectos-comercial", icon: BriefcaseBusiness, number: "03", title: "Proyectos y gestión comercial", intro: "Evaluamos oportunidades con la rigurosidad que exige una inversión minera.", image: projectsImage, items: ["Evaluación de proyectos de inversión", "Análisis de riesgo, VAN, TIR y WACC", "Valorización de concentrados", "Gestión comercial y compra de mineral"] },
  { id: "rentabilidad", detailSlug: "rentabilidad", icon: TrendingUp, number: "04", title: "Rentabilidad que se sostiene", intro: "La consultoría termina cuando las capacidades quedan instaladas en su equipo.", image: profitabilityImage, items: ["Modelos de gestión adaptados al negocio", "Transferencia de conocimiento", "Acompañamiento a usuarios clave", "Medición de impacto y mejora continua"] },
];

export default function Services() {
  return <div className="site-page"><Navbar /><main className="inner-page"><header className="page-header services-header"><p className="eyebrow">Lo que hacemos</p><h1>Soluciones para cada decisión crítica de su operación.</h1><p>Desde el presupuesto hasta la valorización de un proyecto, ayudamos a que la cadena de valor minera funcione como una sola empresa.</p></header><section className="service-visual"><img src={mineralImage} alt="Muestras de mineral y análisis de valor comercial" /><div><p className="eyebrow">Gestión minera integrada</p><h2>Una brecha, un driver, un responsable y un impacto en dólares.</h2><Link href="/contacto" className="detail-link">Conversemos sobre su desafío <ArrowRight size={16} /></Link></div></section><section className="service-list service-grid"><div className="services-grid-heading"><p className="eyebrow">Capacidades JCC</p><h2>Una mirada completa del negocio minero.</h2></div>{groups.map(({ id, detailSlug, icon: Icon, number, title, intro, image, items }) => <article id={id} className="service-card" key={id}><div className="service-card-image" style={{ backgroundImage: `url(${image})` }} /><div className="service-card-body"><div className="service-card-top"><span className="service-number">{number}</span><Icon size={22} strokeWidth={1.4} /></div><h2>{title}</h2><p className="service-intro">{intro}</p><ul>{items.slice(0, 3).map(item => <li key={item}>{item}</li>)}</ul><Link href={`/detalle/${detailSlug}`} className="detail-link">Ver servicio <ArrowRight size={16} /></Link></div></article>)}</section><div className="page-cta"><h2>¿Tiene un desafío específico?</h2><Link href="/contacto" className="button button-dark">Conversemos <ArrowRight size={17} /></Link></div></main><Footer /></div>;
}