import { ArrowRight, BarChart3, BrainCircuit, Calculator, Cloud, Code2, Database, FileSpreadsheet, Gauge, GitBranch, Network, Workflow } from "lucide-react";
import { Link } from "wouter";
import { Navbar } from "@/components/sections/Navbar";
import { Footer } from "./Home";

const corporateTools = [
  { icon: Database, accent: "blue", title: "SAP ERP", text: "Integración centralizada de los flujos de operaciones, logística y finanzas en una sola fuente de verdad corporativa." },
  { icon: BarChart3, accent: "gold", title: "Power BI & Business Intelligence", text: "Dashboards ejecutivos con KPIs analíticos en tiempo real para la toma de decisiones gerenciales." },
  { icon: FileSpreadsheet, accent: "green", title: "Excel Avanzado & Modelamiento", text: "Modelos financieros complejos, control presupuestario y proyecciones de Budget & Forecast." },
  { icon: Calculator, accent: "orange", title: "MS Project & Primavera P6", text: "Cronogramas maestros, análisis de ruta crítica y control estricto de proyectos industriales." },
  { icon: Cloud, accent: "cyan", title: "Integración Cloud & Gobernanza", text: "Sincronización segura de datos entre campo y oficina central, garantizando disponibilidad y cumplimiento." },
];

const transformationSteps = [
  { icon: GitBranch, label: "Mapeo de procesos", tag: "PROCESS MAPPING", text: "Levantamiento y documentación de procesos end-to-end mina–planta–finanzas para identificar cuellos de botella." },
  { icon: Workflow, label: "Automatización robótica", tag: "RPA", text: "Bots de software que ejecutan tareas repetitivas de conciliación, carga de datos y generación de reportes." },
  { icon: BrainCircuit, label: "Machine Learning & modelos predictivos", tag: "PREDICTIVE AI", text: "Algoritmos para anticipar fallas en maquinaria crítica, desviaciones de costos y variables operativas." },
  { icon: BrainCircuit, label: "Deep Learning & Computer Vision", tag: "NEURAL NETWORKS", text: "Redes neuronales profundas para video e imágenes en tiempo real, control automatizado y detección de anomalías." },
  { icon: Database, label: "Arquitectura de datos: SQL & Big Data", tag: "DATA ARCHITECTURE", text: "SQL Server para el núcleo transaccional y Data Lakes para el volumen masivo de sensores y sistemas." },
  { icon: Code2, label: "Python Pipelines & Data Engineering", tag: "BACKEND & ETL", text: "Tuberías ETL automatizadas para limpieza, transformación y procesamiento masivo de múltiples fuentes." },
];

export default function Technology() {
  return <div className="site-page"><Navbar /><main className="inner-page"><header className="page-header"><p className="eyebrow">Modernización tecnológica</p><h1>La tecnología debe responder a la operación, no al revés.</h1><p>Consolidamos el stack tecnológico que su equipo ya utiliza, lo optimizamos y lo conectamos directamente con modelos analíticos avanzados.</p></header><section className="tech-panels"><article><Database size={33} /><p className="eyebrow">01 / SAP PMO minero</p><h2>Un ERP que entiende la realidad de su mina.</h2><p>Coordinamos el proyecto desde el lado de la operación, rediseñando procesos end-to-end antes de configurar la tecnología.</p><ul><li>Modelo de costos y control CAPEX/OPEX</li><li>Estandarización mina–planta–finanzas</li><li>Gestión del cambio para usuarios clave</li></ul></article><article className="orange-panel"><Gauge size={33} /><p className="eyebrow">02 / Automatización inteligente</p><h2>Menos Excel manual. Más tiempo para decidir.</h2><p>Llevamos su planificación financiera al siguiente nivel con FP&A automatizado, dashboards ejecutivos y Business Intelligence.</p><ul><li>Cierre financiero más rápido</li><li>KPIs visibles en tiempo real</li><li>Alianza tecnológica con Partner 247</li></ul></article></section><section className="premium-tech-section"><div className="premium-section-heading"><div><p className="eyebrow">El stack que conecta la operación</p><h2>Herramientas corporativas que sostienen la operación diaria.</h2></div><p>Una arquitectura práctica para que los datos pasen del campo a la decisión sin perder contexto, velocidad ni control.</p></div><div className="tool-grid">{corporateTools.map(({ icon: Icon, accent, title, text }) => <article className="tool-card" key={title}><div className={`tool-icon ${accent}`}><Icon size={21} /></div><h3>{title}</h3><p>{text}</p><span className="card-line" /></article>)}</div></section><section className="premium-tech-section transformation-section"><div className="premium-section-heading"><div><p className="eyebrow">De la operación al modelo</p><h2>Del mapeo del proceso al modelo que lo predice.</h2></div><p>Empezamos entendiendo y ordenando cómo funciona hoy su operación, automatizamos donde hay trabajo repetitivo y elevamos el análisis donde hace falta anticipar el futuro.</p></div><div className="transformation-grid">{transformationSteps.map(({ icon: Icon, label, tag, text }) => <article className="transformation-card" key={label}><div className="transformation-top"><div className="tool-icon violet"><Icon size={20} /></div><span>{tag}</span></div><h3>{label}</h3><p>{text}</p></article>)}</div></section><section className="quote-block"><span>“</span><p>No implementamos tecnología sin antes entender cómo funciona su operación.</p></section><div className="page-cta"><h2>Conectemos su operación.</h2><Link href="/contacto" className="button button-dark">Agendar diagnóstico <ArrowRight size={17} /></Link></div></main><Footer /></div>;
}